PREFIX	r:	<http://kg.course/action/>
PREFIX	e:	<http://kg.course/entity/>
SELECT COUNT(*)
WHERE {
    ?s ?r ?o.
}

# 找出所有一级实体
SELECT DISTINCT ?s
WHERE {
    ?s ?r ?o.
  MINUS{?s r:name ?o}
}

# 删除原著书目、第*季
PREFIX	r:	<http://kg.course/action/>
PREFIX	e:	<http://kg.course/entity/>
DELETE WHERE {?s r:原著書目 ?o.};
DELETE WHERE {?s r:原著书目 ?o.};
DELETE WHERE {?s r:出场季数 ?o.};
DELETE WHERE {?s r:出场集数 ?o.};
DELETE WHERE {?s r:提及集数 ?o.};
DELETE WHERE {?s r:演员 ?o.};
DELETE WHERE {?s r:第一季 ?o.};
DELETE WHERE {?s r:第二季 ?o.};
DELETE WHERE {?s r:第三季 ?o.};
DELETE WHERE {?s r:第四季 ?o.};
DELETE WHERE {?s r:第五季 ?o.};
DELETE WHERE {?s r:第六季 ?o.};
DELETE WHERE {?s r:第七季 ?o.};
DELETE WHERE {?s r:第八季 ?o.};

# 查出所有literal的实体
PREFIX	r:	<http://kg.course/action/>
PREFIX	e:	<http://kg.course/entity/>
SELECT ?o
WHERE {
    ?s ?r ?o.
  FILTER isLiteral(?o)
}

# entity matching
PREFIX	e:	<http://kg.course/entity/>
SELECT DISTINCT *
WHERE{
  {?s r:name ?o
    FILTER regex(?o, ".*艾莉亚.*")}
  UNION{?s r:别名 ?o
  		FILTER regex(?o, ".*艾莉亚.*")}
}

PREFIX	r:	<http://kg.course/action/>
PREFIX	e:	<http://kg.course/entity/>
SELECT DISTINCT ?s
WHERE{{
    {{?s r:name ?o
        FILTER regex(?o, ".*{words}.*")}}
    UNION{{?s r:别名 ?o
        FILTER regex(?o, ".*{words}.*")}}
    UNION{{?s r:名 ?o
        FILTER regex(?o, ".*{words}.*")}}
}}

PREFIX	r:	<http://kg.course/action/>
PREFIX	e:	<http://kg.course/entity/>
SELECT DISTINCT ?s ?r ?o
WHERE {
    ?s ?r ?o.
    MINUS {?s r:type ?o}
    MINUS {?s r:name ?o}
    MINUS {?s r:名 ?o}
  	 MINUS {?s r:姓 ?o}
    MINUS {?s r:别名 ?o}
#    MINUS {{entity} ?r ?o}
#  	FILTER regex(str(?r), "现任领主")
  FILTER isLiteral(?o)
#  	FILTER regex(?o, "^攸伦.*$")
}

# debug: 看有没有实体的name属性被删除了
PREFIX	r:	<http://kg.course/action/>
PREFIX	e:	<http://kg.course/entity/>
SELECT DISTINCT ?s
WHERE{
  ?s ?r ?e
  FILTER EXISTS{?s r:name ?o}
}


PREFIX	r:	<http://kg.course/action/>
PREFIX	e:	<http://kg.course/entity/>
SELECT DISTINCT *
WHERE {
    ?s ?r ?o.
  MINUS{
    ?s ?r ?o
    FILTER isLiteral(?o)
  }
}